// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/control-gate": {
            "get": {
                "description": "回傳 保全狀態",
                "tags": [
                    "controlGate"
                ],
                "summary": "取得保全狀態",
                "responses": {
                    "200": {
                        "description": "no content"
                    }
                }
            },
            "post": {
                "description": "更新保全狀態",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "controlGate"
                ],
                "summary": "更新保全狀態(上班/下班)",
                "parameters": [
                    {
                        "description": "更新請求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controlGate.ControlGateUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controlGate.ControlGateResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/devices/{id}/state": {
            "post": {
                "description": "新增一筆 on/off 事件，並同步裝置當前狀態（create on/off event and sync device state）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "改變裝置狀態（change device state）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "裝置 id（device id）",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "請求內容（payload）",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rooms.ChangeDeviceStateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "no content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "控制被拒（例如總電閘關閉 control gate off）",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "回傳 pong（return pong）",
                "tags": [
                    "health"
                ],
                "summary": "Ping 測試（ping test）",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/rooms": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "列出所有房間（list all rooms）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            }
        },
        "/rooms/devices/state": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "查詢房間內裝置狀態",
                "parameters": [
                    {
                        "type": "string",
                        "description": "房間名稱 (room name)",
                        "name": "room_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "房間 IDs (逗號分隔)",
                        "name": "ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controlGate.ControlGateResp": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "controlGate.ControlGateUpdateReq": {
            "type": "object",
            "required": [
                "enabled"
            ],
            "properties": {
                "enabled": {
                    "type": "boolean"
                }
            }
        },
        "rooms.ChangeDeviceStateReq": {
            "type": "object",
            "required": [
                "is_on"
            ],
            "properties": {
                "is_on": {
                    "type": "boolean"
                },
                "note": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Smart Home API (smart home api)",
	Description:      "裝置/房間狀態管理 API（devices/rooms state management api）",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
