basePath: /
definitions:
  controlGate.ControlGateResp:
    properties:
      enabled:
        type: boolean
      updated_at:
        type: string
    type: object
  controlGate.ControlGateUpdateReq:
    properties:
      enabled:
        type: boolean
    required:
    - enabled
    type: object
  event.EventResp:
    properties:
      device_id:
        type: integer
      device_name:
        type: string
      event_id:
        type: integer
      event_timestamp:
        type: string
      is_open:
        type: boolean
      room_id:
        type: integer
      room_name:
        type: string
    type: object
  rooms.ChangeDeviceStateReq:
    properties:
      is_on:
        type: boolean
      note:
        type: string
    required:
    - is_on
    type: object
host: localhost:8080
info:
  contact: {}
  description: 裝置/房間狀態管理 API（devices/rooms state management api）
  title: Smart Home API (smart home api)
  version: "1.0"
paths:
  /control-gate:
    get:
      description: 回傳 保全狀態
      responses:
        "200":
          description: no content
      summary: 取得保全狀態
      tags:
      - controlGate
    post:
      consumes:
      - application/json
      description: 更新保全狀態
      parameters:
      - description: 更新請求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controlGate.ControlGateUpdateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controlGate.ControlGateResp'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 更新保全狀態(上班/下班)
      tags:
      - controlGate
  /devices/{id}/state:
    post:
      consumes:
      - application/json
      description: 新增一筆 on/off 事件，並同步裝置當前狀態（create on/off event and sync device state）
      parameters:
      - description: 裝置 id（device id）
        in: path
        name: id
        required: true
        type: integer
      - description: 請求內容（payload）
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/rooms.ChangeDeviceStateReq'
      produces:
      - application/json
      responses:
        "200":
          description: no content
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "409":
          description: 控制被拒（例如總電閘關閉 control gate off）
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: 改變裝置狀態（change device state）
      tags:
      - devices
  /events:
    get:
      description: 可以依時間區間和房間過濾
      parameters:
      - description: 開始時間 (RFC3339 格式)
        in: query
        name: start
        type: string
      - description: 結束時間 (RFC3339 格式)
        in: query
        name: end
        type: string
      - description: 房間 ID
        in: query
        name: room_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/event.EventResp'
            type: array
      summary: 查詢事件
      tags:
      - events
  /ping:
    get:
      description: 回傳 pong（return pong）
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping 測試（ping test）
      tags:
      - health
  /rooms:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
      summary: 列出所有房間（list all rooms）
      tags:
      - rooms
  /rooms/devices/state:
    get:
      parameters:
      - description: 房間名稱 (room name)
        in: query
        name: room_name
        type: string
      - description: 房間 IDs (逗號分隔)
        in: query
        name: ids
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
      summary: 查詢房間內裝置狀態
      tags:
      - rooms
swagger: "2.0"
