basePath: /
host: localhost:8080
info:
  contact: {}
  description: 裝置/房間狀態管理 API（devices/rooms state management api）
  title: Smart Home API (smart home api)
  version: "1.0"
paths:
  /ping:
    get:
      description: 回傳 pong（return pong）
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping 測試（ping test）
      tags:
      - health
  /rooms:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
      summary: 列出所有房間（list all rooms）
      tags:
      - rooms
  /rooms/devices/state:
    get:
      parameters:
      - description: 房間名稱 (room name)
        in: query
        name: room_name
        type: string
      - description: 房間 IDs (逗號分隔)
        in: query
        name: ids
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
      summary: 查詢房間內裝置狀態
      tags:
      - rooms
swagger: "2.0"
